### ISSUE TITLE
Заредете номенклатурата

### ISSUE THREAD

**Issue by Nikson998** [thefinalcutbg/OpenPrescription#1]
Здравейте,

Инсталирах OpenPrescription ver 0.9 на Windows 10 с 64 битов процессор. Windows-a е на български.
И този прозорец ми изкача след първото отваряне и пробване за добавяне на prescription.

<img width="1236" alt="Screenshot 2023-11-08 at 15 40 45" src="https://github.com/thefinalcutbg/OpenPrescription/assets/150258832/718cd062-cae1-4082-9758-0e53b045f7cf">

Ще може ли да помогнете за решаване на проблема. Благодаря предварително.

**Comment by thefinalcutbg** [comment]
По принцип номенклатурата би трябвало да се свали сама при стартирането на програмата. Ако излезете от програмата и влезете пак, дава ли Ви отново да въведете данните си (УИН, РЗИ номер и т.н.)?
________________________________
From: Nikson998 ***@***.***>
Sent: Wednesday, November 8, 2023 15:42
To: thefinalcutbg/OpenPrescription ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [thefinalcutbg/OpenPrescription] Заредете номенклатурата (Issue #1)


Здравейте,

Инсталирах OpenPrescription ver 0.9 на Windows 10 с 64 битов процессор. Windows-a е на български.
И този прозорец ми изкача след първото отваряне и пробване за добавяне на prescription.

[Screenshot 2023-11-08 at 15 40 45]<https://user-images.githubusercontent.com/150258832/281421063-718cd062-cae1-4082-9758-0e53b045f7cf.png>

Ще може ли да помогнете за решаване на проблема. Благодаря предварително.

**Comment by Nikson998** [comment]
Не, те си стоят запомнени.
Но при всяко натискане на бутона "Добави" се изписва съобщението и не може да се процедира по-натам.

**Comment by thefinalcutbg** [comment]
Имате ли антивирусна или firewall, които биха могли да блокират достъпа на програмата до интернет?
________________________________
